### ISSUE TITLE
用正则预处理log的一些问题

### ISSUE THREAD

**Issue by zxkane** [AliyunContainerService/fluentd-pilot#22]
1. `pilot`支持什么语言下的正则处理？是`go`，`ruby`还是其他什么语言?
一段Java下正确执行的正则表达式，在通过SLS控制台添加`Logtail`验证的时候就是无效的。
1. 通过`Logtail`输入正则的时候，可以提取字段，并为每个字段指定key。为`pilot`指定log的正则格式时，如何指定字段的key呢？通过named-capturing可以做到吗？

**Comment by jzwlqx** [comment]
和ruby的正则类似，fluentd文档上给了几个例子

**Comment by zxkane** [comment]
为container添加了format相关的label后，`pilot`仍然发送的是整条log，没有按预期用regexp分解log发送key/value。看了`pilot`的log，也没有有用的信息。这种情况如何分析解决？

```shell
            "Labels": {
                "aliyun.logs.svt-apps": "stdout",
                "aliyun.logs.svt-apps.format": "regexp",
                "aliyun.logs.svt-apps.format.pattern": "(?<time>\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d{3})\\s(?<level>[A-Z]+)\\s\\[(?<servicename>[\\w-_]+),(?<trackid>[a-z0-9]*),(?<spanid>[a-z0-9]*),(?<key>\\w*)]\\s(?<pid>\\d+)\\s---\\s\\[(?<threadname>.+)]\\s(?<loggername>[\\w\\.]+)\\s+:\\s+(?<message>.*)",
                "aliyun.logs.svt-apps.tags": "name=magiceye",
```

**Comment by zxkane** [comment]
正则处理log不工作应该如何分析？

**Comment by jzwlqx** [comment]
这个问题其实是因为docker把stdout保存了json格式，所以对stdout强制成json format，这里你设置的regexp就没生效。

不过确实要考虑下是不是要支持stdout设置成其他格式

**Comment by zxkane** [comment]
`pilot`目前要处理这种log的话，我需要把log作为文件写到container内，然后让`pilot`处理container内的log文件？

**Comment by jzwlqx** [comment]
目前是这样。

**Comment by jzwlqx** [comment]
I will close this issue and give an solution later.

**Comment by mengskysama** [comment]
试了下目前版本任然不支持stdout的正则匹配，请问有没有计划支持？
