### ISSUE TITLE
k8s中Pod设置的metadata.labels 规则是 (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?，不能有“/”，这个怎么破

### ISSUE THREAD

**Issue by softdzx** [AliyunContainerService/fluentd-pilot#27]
ReplicationController "demo-86" is invalid: [spec.selector: Required value, spec.template.labels: Invalid value: "/demo/logs/*.log": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')].

**Comment by softdzx** [comment]
K8S 部署的Pod 应用容器中是无法获取--label为aliyun.logs.*** 的
"Labels": {
                "io.kubernetes.container.hash": "947ade32",
                "io.kubernetes.container.name": "official-demo",
                "io.kubernetes.container.restartCount": "0",
                "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "io.kubernetes.pod.name": "official-demo-115-owzta",
                "io.kubernetes.pod.namespace": "default",
                "io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.pod.uid": "0379c704-2644-11e7-9778-fc4dd4db354b"
            }

建议也支持从Config.Env 获取配置的日志路径；优先从Config.Labels 中获取，如果没有就从Config.Env中获取；这样就能兼容使用k8s来部署管理应用的用户了；小小建议仅供参考。

**Comment by jzwlqx** [comment]
k8s的支持在规划中，即将开始。

**Comment by BSWANG** [comment]
@softdzx 参考上面这个PR，目前可以支持环境变量获取日志的配置，以及将pod的信息作为tag上传。
