### ISSUE TITLE
新增了一些功能支持通过环境变量设置日志配置，好像无法提交PR;

### ISSUE THREAD

**Issue by softdzx** [AliyunContainerService/fluentd-pilot#28]
支持这样，方便k8s等第三方支持
docker run -it --rm  -p 10080:8080 \
-v /usr/local/tomcat/logs \
-e ALIYUN_LOGS_CATALINA=stdout \
-e ALIYUN_LOGS_ACCESS=/usr/local/tomcat/logs/localhost_access_log.*.txt \
tomcat

**Comment by BSWANG** [comment]
提交PR直接fork到自己的账号或者组织下，然后提交到自己的分支后提交Pull Request就好了。
