### ISSUE TITLE
tags中添加target，并未用target的值作为索引？？？

### ISSUE THREAD

**Issue by softdzx** [AliyunContainerService/fluentd-pilot#32]
aliyun.logs.access.tags="target=abc,name=hello,stage=test"，并没有用target来做索引，而是用来做了普通的字段，索引还是access，？？？

应该是从tagMap中获取target吧，看源码是在info中获取的target
target := info.get("target")

还有一个问题，就是怎么根据时间来生成target值；有好的办法吗

**Comment by softdzx** [comment]
是pilot.go 中201 行代码引起的
if len(envLabel) == 2 {

**Comment by softdzx** [comment]
修改2处代码解决，已测试通过：

修改newContainer 方法中读取env

	for _, v := range env {
	   if !strings.HasPrefix(v, ENV_SERVICE_LOGS){
		  continue
	   }
	   ind := strings.Index(v, "=")
	   rl := len(v)
	   key := strings.ToLower(v[0:ind])
	   key = strings.Replace(key, "_", ".", -1)
	   labels[key]=v[ind+1:rl]
    }

修改parseLogConfig方法中获取target
target := tagMap["target"]

**Comment by jzwlqx** [comment]
@softdzx 在最新的版本里，target指定的方式从tags里面提升到一个单独的label里， 参考

https://github.com/AliyunContainerService/fluentd-pilot/blob/master/docs/docs.md
> aliyun.logs.$name.target=target-for-log-storage: target is used by the output plugins, instruct the plugins to store logs in appropriate place. For elasticsearch output, target means the log index in elasticsearch. For aliyun_sls output, target means the logstore in aliyun sls. The default value of target is the log name.

这种方式分离的tags和target的语义，使用起来更清晰。你可以尝试用新的方式配置。

抱歉，给你带来了困扰
