### ISSUE TITLE
请教一个关于 log-driver 的问题

### ISSUE THREAD

**Issue by knarfeh** [AliyunContainerService/fluentd-pilot#34]
打扰各位，有个疑问，还没细看代码，想着在这边问一下可能更快一点。
既然是用 fluentd 收集日志，为什么
```
docker run -it --rm  -p 10080:8080 \
    -v /usr/local/tomcat/logs \
    --label aliyun.logs.catalina=stdout \
    --label aliyun.logs.access=/usr/local/tomcat/logs/localhost_access_log.*.txt \
    tomcat
```
这个例子不需要指定 --log-driver 呢，就像这样：`docker run --log-driver=fluentd --log-opt fluentd-address=fluentdhost:24224 image:latest
`
请问是怎么做到的，还请不吝赐教。

**Comment by jzwlqx** [comment]
log driver只能收集stdout日志，不支持文件日志。要收集文件日志就没办法了。
