### ISSUE TITLE
无法收集docker service create方式创建的服务，有解决方案吗？

### ISSUE THREAD

**Issue by yangwf** [AliyunContainerService/fluentd-pilot#54]
无法收集docker service create方式创建的服务，初步判断原因，aliyun.logs.XXX  label，只在docker service inspect ”服务名”可见，在分派的具体任务容器上不可见。
docker service create方式创建的服务，容器级别的label好像是系统级固定的，比如：
"Labels": {
                "build-date": "2016-06-02",
                "com.docker.swarm.node.id": "hmgn87d2lb8bulm6jyr2l7vqx",
                "com.docker.swarm.service.id": "n4srslf98cnm7mhmg1cs4moei",
                "com.docker.swarm.service.name": "tengine",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "rvngmkp7rxcauu9kn24f45f30",
                "com.docker.swarm.task.name": "tengine.2.rvngmkp7rxcauu9kn24f45f30",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }

**Comment by BSWANG** [comment]
Use the `[container-label](https://docs.docker.com/engine/reference/commandline/service_create/#options)` options on service creating.
