### ISSUE TITLE
unmount失败造成Dev环境k8s无法启动

### ISSUE THREAD

**Issue by mengskysama** [AliyunContainerService/fluentd-pilot#59]
umount: can't unmount /host/var/lib/docker/containers/ea086c82f703f6340656a7e439b7ba1ce62fcfc25943eb18f069f4addff1965e/shm: Operation not permitted
Traceback (most recent call last):
  File "/pilot/entrypoint", line 40, in <module>
    cleanup()
  File "/pilot/entrypoint", line 30, in cleanup
    umount(volume)
  File "/pilot/entrypoint", line 14, in umount
    subprocess.check_call('umount -l %s' % volume, shell=True) 
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'umount -l /host/var/lib/docker/containers/ea086c82f703f6340656a7e439b7ba1ce62fcfc25943eb18f069f4addff1965e/shm' returned non-zero exit status 1
[root@izbp1h89rekgh0fwkpm976z ~]# 

这个上来就umount是为了避免产生垃圾？
*/.    .   .    *      .
  .\*    .    []           *  __
  */ .   ./\~~~~~~~~~~~~'\. |◆  
   \*   ,/,..,\,...........,\.◆  
   ||  ..▎#  ▎田  田 ▎ | ▎◆
   ||  &&▎   ▎       ▎'|'▎ o   
   || ##■■■■■■■■■■〓

**Comment by BSWANG** [comment]
`umount shm`是避免别的容器不能被删除导致产生垃圾，umount需要容器中有privileged或者CAP-SYSADMIN权限，所以需要给这个容器分配umount的权限
