### ISSUE TITLE
挂载 / 根分区，导致系统无法卸载设备 Device or resource busy  

### ISSUE THREAD

**Issue by zongmry** [AliyunContainerService/fluentd-pilot#61]
你好，
创建 fluentd-pilot 容器时，使用参数 -v /:/host，导致系统频繁报错，rnode-4 systemd-logind: Failed to remove runtime directory /run/user/0: Device or resource busy 或者 remove /var/lib/docker/containers/cd5de061ad2a304d90f8766270e0782a16b15db649fb7d1a33d754d71243ba59/shm: device or resource busy" 

环境
17.05.0-ce On CentOS 7.3

命令
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:0.0.3

请帮忙看下，谢谢。

**Comment by BSWANG** [comment]
我看你的版本还是0.0.3,请用最新构建的latest版本试一下，最新的latest版本会在容器中umount那些目录，保证不会报busy

**Comment by BSWANG** [comment]
umount需要privileged权限 
```
docker run --rm -it 
--privileged
-v /var/run/docker.sock:/var/run/docker.sock 
-v /:/host 
registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest
```

**Comment by zongmry** [comment]
问题解决了，谢谢指导。
