### ISSUE TITLE
请问针对k8s， fluentd-pilot这套方案如何使用？

### ISSUE THREAD

**Issue by tianlin** [AliyunContainerService/fluentd-pilot#73]
k8s不支持将LABEL 给 POD中的container，如果我要采POD中Container的日志，那fluentd-pilot方案还能使用么？

**Comment by BSWANG** [comment]
fluentd-pilot use env to support k8s pod container.

**Comment by better0332** [comment]
阿里的k8s对环境变量aliyun_logs_做了挂盘处理吧？
