### ISSUE TITLE
最新版acs-sample/fluentd-pilot：latest镜像部署时提示没有权限

### ISSUE THREAD

**Issue by jushiyuan** [AliyunContainerService/fluentd-pilot#76]
umount: can't unmount /host/var/lib/docker/containers/e80cc870732f4b1b2374845ecc41d80e42e92e03ad5e553a829091c61b4ee50b/shm: Operation not permitted
Traceback (most recent call last):
  File "/pilot/entrypoint", line 40, in &lt;module&gt;
    cleanup()
  File "/pilot/entrypoint", line 30, in cleanup
    umount(volume)
  File "/pilot/entrypoint", line 14, in umount
    subprocess.check_call('umount -l %s' % volume, shell=True) 
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'umount -l /host/var/lib/docker/containers/e80cc870732f4b1b2374845ecc41d80e42e92e03ad5e553a829091c61b4ee50b/shm' returned non-zero exit status 1

**Comment by BSWANG** [comment]
fluentd-pilot运行需要privileged权限

**Comment by jushiyuan** [comment]
这个问题是解决了，但是部署到k8s集群中还是无法收集日志。之前用的阿里提供的wangbs/fluentd-pilot：latest镜像是可以的，但是镜像版本很老有些bug，能否把这个镜像更新到最新版？谢谢

**Comment by jushiyuan** [comment]
使用wangbs/fluentd-pilot这个镜像的时候，是不用设置privileged权限就能用的

**Comment by BSWANG** [comment]
@chenqz1987

**Comment by chenqz1987** [comment]
可以在fluentd-pilot容器里确认下是否在/etc/fluentd/conf.d/下生成了日志收集配置文件，另外也可以看下对应节点上fluentd-pilot容器的日志

**Comment by jushiyuan** [comment]
@chenqz1987 我搞错了不好意思，现在收集到了，但是在我设置的target后面加了个时间戳。比如我设置的是的aliyun_logs_$name_target：test，但是收集的时候变成target-2018.01.11了

**Comment by BSWANG** [comment]
如果日志输出到elasticsearch的话，这个是加了时间戳在target后面的，为了对方便对时序的日志进行统一的管理，这个跟这个issue不是同一个，所以我先关掉这个issue了，如果关于target名字还有疑问，也可以随时在这个issue中继续评论。

**Comment by jushiyuan** [comment]
这个时间戳是根据什么取的呢
